Update

diff --git a/zprezto/runcoms/zshenv b/zprezto/runcoms/zshenv
--- a/zprezto/runcoms/zshenv
+++ b/zprezto/runcoms/zshenv
@@ -14,7 +14,7 @@ fi
 export TERM="xterm-256color"
 
 # Rust
-export RUST_BACKTRACE=1
+# export RUST_BACKTRACE=1
 # export RUSTC_WRAPPER=sccache
 
 if [[ -s "$HOME/.cargo/env" ]]; then
@@ -37,11 +37,63 @@ if [ -e $HOME/.nix-profile/etc/profile.d/nix.sh ]; then
   source $HOME/.nix-profile/etc/profile.d/nix.sh;
 fi # added by Nix installer
 
-# GitHub Copilot
-# eval "$(github-copilot-cli alias -- "$0")"
-
 # zoxide
 eval "$(zoxide init zsh)"
 
 # Aliases
 source "$HOME/.aliases"
+
+# GitHub Copilot
+# eval "$(github-copilot-cli alias -- "$0")"
+
+copilot_what-the-shell () {
+    TMPFILE=$(mktemp);
+    trap 'rm -f $TMPFILE' EXIT;
+    if /opt/homebrew/bin/github-copilot-cli what-the-shell "$@" --shellout $TMPFILE; then
+      if [ -e "$TMPFILE" ]; then
+        FIXED_CMD=$(cat $TMPFILE);
+        print -s "$FIXED_CMD";
+        eval "$FIXED_CMD"
+      else
+        echo "Apologies! Extracting command failed"
+      fi
+    else
+      return 1
+    fi
+  };
+alias '??'='copilot_what-the-shell';
+
+  copilot_git-assist () {
+    TMPFILE=$(mktemp);
+    trap 'rm -f $TMPFILE' EXIT;
+    if /opt/homebrew/bin/github-copilot-cli git-assist "$@" --shellout $TMPFILE; then
+      if [ -e "$TMPFILE" ]; then
+        FIXED_CMD=$(cat $TMPFILE);
+        print -s "$FIXED_CMD";
+        eval "$FIXED_CMD"
+      else
+        echo "Apologies! Extracting command failed"
+      fi
+    else
+      return 1
+    fi
+  };
+alias 'git?'='copilot_git-assist';
+
+  copilot_gh-assist () {
+    TMPFILE=$(mktemp);
+    trap 'rm -f $TMPFILE' EXIT;
+    if /opt/homebrew/bin/github-copilot-cli gh-assist "$@" --shellout $TMPFILE; then
+      if [ -e "$TMPFILE" ]; then
+        FIXED_CMD=$(cat $TMPFILE);
+        print -s "$FIXED_CMD";
+        eval "$FIXED_CMD"
+      else
+        echo "Apologies! Extracting command failed"
+      fi
+    else
+      return 1
+    fi
+  };
+alias 'gh?'='copilot_gh-assist';
+alias 'wts'='copilot_what-the-shell';
